// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dniuodtuqikcxdatwcpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaXVvZHR1cWlrY3hkYXR3Y3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTEyMTMsImV4cCI6MjA3MTQyNzIxM30.FRoSO0VHNRAfaqzCSDusN5HlW6WkeLO98W2kN9L6avc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});